### ISSUE TITLE
Bulk editing not working

### ISSUE THREAD

**Issue by ClaraDOAJ** [DOAJ/doaj#1303] opened 2017-05-18 08:16 UTC
Hello CL,

An email from my colleague. Please, can you help?

Hi Clara,

I never have any success with the bulk editor! 

I have tried to add a note to a group of journals, before then rejecting them. But it has come back with an error. It looks as if I am not allowed to add a note as I am not the editor. I cannot change the editor group via bulk edit as it won't work if an assistant editor is already selected (that was my previous unsuccessful attempt at bulk editing). So I guess I can't reject them either, as I am not the editor.

I am left with having to do them all individually because the bulk editor is effectively useless.

Frustratedly,

here you have the error

Your background job 5e1eb55629cd4b91b4c580f4a329db90 for "suggestion_bulk_edit" has finished with status "error"

You can see the record of your job and its status in the background jobs interface here:

https://doaj.org/admin/background_jobs?source=%7B%22query%22%3A%7B%22query_string%22%3A%7B%22query%22%3A%225e1eb55629cd4b91b4c580f4a329db90%22%2C%22default_operator%22%3A%22OR%22%7D%7D%7D

**Comment by richard-jones** [comment] 2017-05-18 14:14
This is an odd one - the error is saying that the validation error is that the editor is not in the editor group, but the action is to add a note.

There is no editor_group set during this add_note operation, which would suggest that the Applications themselves are outdated in the database.  Looking at the code and the logs, I am basically certain the background job is not touching the editor or editor_group fields.

The error is correct that the editor "falk" is not in the group "German1".  Was there a point where editor "falk" was in that group, and has subsequently been removed?  I can't see a record of a user called "falk" in the system, perhaps that account was deleted?

**Comment by ClaraDOAJ** [comment] 2017-05-18 14:20
Hi
I even gave my colleague the "ultra bulk edit" privileges and this did not help either. I think my colleague tried to bulk change the editor group so she was the editor for that group, but she could not as there was an editor already assigned to that group of journals...

mm.. what do you suggest?

Many many thanks!

Clara

**Comment by Steven-Eardley** [comment] 2017-05-18 14:23
I think the bulk action interface validates the whole record in the same way as the edit form does, even on fields that aren't specifically being changed. So if the record is broken it won't save properly, and would need individual attention.

**Comment by ClaraDOAJ** [comment] 2017-05-18 14:29
mmm..and how do we know if a record is broken? and why could a record be broken?
Apologies for silly questions...

**Comment by emanuil-tolev** [comment] 2017-05-18 14:35
I'm inclined to agree with @Steven-Eardley , I think the bulk edit functionality is highlighting potential data problems that might have been fixed on a one-off basis by the editorial team otherwise. I think this is a good thing actually (much better data consistency and quality), albeit I'm sure a little frustrating to the team.

For this particular issue, if you actually open the form the Editor field stays on "Choose an Editor..." rather than reporting it's "falk". https://doaj.org/admin/suggestion/5158c2f74b884fa0ad54606202a94c7b

So on the web form, a user would never try to set "falk" as the Editor and "German1" as the Editor Group. On the web, a user will just appear to want to set "German1" as the Editor Group and nothing more - which is allowed.

Internally the record does seem to include `falk`:

```json
{
      "editor_group": "German1",
      "editor": "falk"
}
```

The Editor field is actually optional in the web form, so it should not stop the bulk functionality from working. I think some validation like "is this editor in this editor group" *is* stopping it from working though.

This could well just be a relational integrity issue. If "falk" was removed as a user we should remove all assignments to them in the system.

**Comment by emanuil-tolev** [comment] 2017-05-18 14:41
Action:

1. check "Delete this user" removes editorial assignments. Add the functionality if not. 

    (Are there any references to usernames? Those should be removed too, like editor group memberships and anything else that uses the username.)

2. Write a migration that checks all editors assigned to an application actually exist as user accounts.

    This can be sped up by retrieving a list of all users with a relevant editor (admin, managing editor, editor, associate editor) role in the beginning of the migration and keeping it in memory. The migration can be written as an iteration over all applications, removing the assignment if the username is not a valid editor.

    (Are there any other places where we use usernames to assign stuff? Again I don't think so but triple-check.)

**Comment by ClaraDOAJ** [comment] 2017-05-18 14:42
Anything I can do to help?

**Comment by emanuil-tolev** [comment] 2017-05-18 14:43
@ClaraDOAJ you might be able to help with 

> Are there any references to usernames in the system?

except where we refer to Editors? Do you use the usernames in your daily work for anything else?

I don't believe there are any other uses of usernames after a brief check, but best to ask somebody who does editorial work with the system every day.

**Comment by ClaraDOAJ** [comment] 2017-05-18 14:50
I do use usernames on daily basis. Sometimes I need to merge accounts, look how many journals a user has, reset passwords, etc.

**Comment by emanuil-tolev** [comment] 2017-05-18 14:59
> I do use usernames on daily basis. Sometimes I need to merge accounts, look how many journals a user has, reset passwords, etc.

Merging accounts and resetting passwords should be OK as that's just account management. It's where other things depend on usernames - that's what I'm interested in.

Journal ownership is certainly one of those, but I don't think we can just leave the owner empty. (1. you delete an account; 2. what do we do with a journal that belonged to that account?) Would be good to decide on what action the system should take here.

**Comment by ClaraDOAJ** [comment] 2017-05-18 15:06
If I delete an account I am  not sure what happens with the journals attached to that account - they might be deleted as well!! 

We have deleted accounts as long as the journals that belonged to that account have been attached to a new user..

**Comment by richard-jones** [comment] 2017-05-18 15:09
To summarise (partially for myself):  

There was once a user called falk who was in the German1 group.  This user has been deleted for time and reasons unknown.  The result is that references to this user still exist, but they are dud (a consequence of a document-oriented system rather than relational system).  

This means when we try to push such an Application through validation, validation fails because the assigned user can't be found.

This has never been noticed before because the user interface automatically strips unknown users from the Application metadata when it renders the choices an editor has to select an associate editor.  But the background jobs do not strip unknown users, and instead throw validation errors.

What are our ways forward with this?  Emanuil lists some tasks above that we can do:

1. Enhance user account removal, so that it knows how to remove users from places they might be referenced (or take other actions related to removed users)

2. Run a data cleanup on the existing database to remove references to dud users

We might also consider a third option, which would give us a quick fix:

3. If an editor cannot be found, the form validation should remove them before validating.  This would help in the current situation, but we'd need to check what impact this has on the application form

**Comment by ClaraDOAJ** [comment] 2017-05-18 15:15
Ah, I understand! interesting. 

Is it possible to do a quick fix now, but think what would be the better approach for the near future? Especially now that we are implementing more bulk-edit features?

**Comment by emanuil-tolev** [comment] 2017-05-18 15:15
That's right @richard-jones . If we can plug the data relationships hole then 3. should never be necessary. It depends on how much time 1+2 vs 3 take I suppose. IMO 1 and 3 would take a very similar amount of time, so it's 2 (the migration) which will add extra time. If we keep the migration restricted to only deal with removing editors who don't have editorial privileges or don't exist, I don't think that should take too long to write.

The other questions I've asked (e.g. journal ownership) are not directly related to solving this issue. They are scoping out any work necessary to prevent similar problems in other parts of the system.

**Comment by ClaraDOAJ** [comment] 2017-05-23 10:52
Hi

My colleague is still having problems with this. She has just been able to set an individual record to rejected, without it causing an error regarding the editor falk. So the bulk edit is doing something extra that is not needed. 

Please this is urgent and it is causing a lot of wasted time. Could you help?

Thanks

**Comment by richard-jones** [comment] 2017-05-23 11:11
Yes, the application form will blank out the unfound editor when you load the form, so doing this individually won't create an error.

I think the only thing that we can do is to modify the bulk edit system to also blank out this field if the editor is not found.  I'll try to look at that before the call this afternoon.

**Comment by emanuil-tolev** [comment] 2017-05-23 11:20
This is a data issue. Can we fix the data with a migration instead, and ensure the delete user functionality blanks the data appropriately?

I feel like blanking it out in the bulk editing system is adding lines of code just to deal with a very specific data issue caused by another part of the system. There could be more of those in the future, so adding workarounds doesn't seem sustainable - better to fix the data at source. This will also avoid any problems caused by non-existent editors elsewhere (besides bulk editing). I'd like to keep the code cleaner while still fixing this. I'd be happy to try to write a migration today in line with what I've proposed above @richard-jones ?

**Comment by ClaraDOAJ** [comment] 2017-05-23 11:24
Hello,
My colleague flagged up that there's also another problem with the bulk edit - if we want to change editor group, but there is an editor assigned, it won't work, as it will leave the editor in place. But again the manual edit doesn't do this.

Please, could you have a look at this as well?

Thanks!

**Comment by richard-jones** [comment] 2017-05-23 11:32
@ClaraDOAJ - that last issue should have been fixed by a recent update, is it still happening?  Could you point me to a job where this is the cause of failure so I can take a look?

@emanuil-tolev - yes, that would be the best approach, but there's a tension between how long that would take and how urgently this is needed, if I understand correctly.  Parity between the application form behaviour and the bulk edit behaviour is also reasonably sensible.

**Comment by richard-jones** [comment] 2017-05-23 12:39
@ClaraDOAJ - I've just had a look into the problem with changing editor group when an editor is assigned, and there is code on the live system which should fix this.  I can't see a background job where that error has occurred recently

The last record I can find where this happened is from a month ago:

https://doaj.org/admin/background_jobs?source=%7B%22query%22%3A%7B%22filtered%22%3A%7B%22filter%22%3A%7B%22bool%22%3A%7B%22must%22%3A%5B%7B%22term%22%3A%7B%22status.exact%22%3A%22error%22%7D%7D%5D%7D%7D%2C%22query%22%3A%7B%22query_string%22%3A%7B%22query%22%3A%227c4faab25a6d4d35bd79a793e9191928%22%2C%22default_operator%22%3A%22AND%22%7D%7D%7D%7D%2C%22sort%22%3A%5B%7B%22created_date%22%3A%7B%22order%22%3A%22desc%22%7D%7D%5D%2C%22from%22%3A0%2C%22size%22%3A25%7D

Can you confirm that it is still happening today?

**Comment by ClaraDOAJ** [comment] 2017-05-23 12:42
I have asked my colleague and she will test it later today.
Thanks

**Comment by emanuil-tolev** [comment] 2017-05-23 20:15
@ClaraDOAJ The issue with "falk" and editor group "German1" should not be a problem on live anymore. Could you ask Judith to retry whatever bulk action she was intending to perform? 

I'm leaving this issue open because the situation could happen again in the future if the data goes wrong by deleting an assigned editor account again. The next step is to fix the delete user functionally so it unassigns the editor being deleted. 

Overall I would say (cc Judith :)) that it is fantastic that this has cropped up during bulk editing. Bulk editing is by necessity different to manual web form editing and we don't have the user-friendly web browser helping us with filling out default values for fields like "editor". This has now plugged a data problem in journals and applications. I understand it's frustrating for Judith (and you, and the other managing editors) but it's helpful to data consistency and system health. What we can do is to try to investigate and diagnose these bulk edit issues as quickly as possible to minimise frustration while reaping the benefits.

**Comment by emanuil-tolev** [comment] 2017-05-23 20:44
Tech note: output from migration on live. Failed suggestion loads are nothing to worry about for now, I checked them manually for the editor field issue. 

```
Running in production
Loaded final config from /home/cloo/repl/production/doaj/src/doaj/production.cfg
writing  389
389 journals were updated, 0 were left unchanged, 0 failed.
Failed to create a suggestion model
no model        5ce92db6dae64da89b8fea754d66624e
Failed to create a suggestion model
no model        b22a79d7bb4a433d97a09126f659c25e                             writing  676
676 suggestions were updated, 0 were left unchanged, 2 failed.
```

**Comment by ClaraDOAJ** [comment] 2017-05-24 08:36
Hi CL
This has worked! Many many thanks :)

**Closed** 2017-05-30 09:25 UTC
Labels: bug, high priority, in progress
