### ISSUE TITLE
 (RIFOP) and  (REIFOP) ISSN problems

### ISSUE THREAD

**Issue by ClaraDOAJ** [DOAJ/doaj#1318] opened 2017-06-09 10:19 UTC
Hello CL

(RIFOP) has two ISSN, and (REIFOP) has only the E-ISSN

As the editor noticed, we have two records with the same associated articles, probably due to the fact that the print ISSN of the first has been put by mistake in the second.

I removed the print ISSN from the REIFOP journal and also tried to delete and reinstate the journal, but nothing is happening and the wrong articles are still there https://doaj.org/toc/1575-0965

How can we sort this out?
Many thanks!

**Comment by emanuil-tolev** [comment] 2017-06-09 15:36
Almost all articles have an ISSN attached (ideally all articles). When you load a journal's ToC page, the the articles that have ISSNs matching those of the journal are displayed.

Removing the ISSN should have been enough.

However, I can see that e.g.:

1. article https://doaj.org/article/01a69660279a4949811301c09ddd77be has `ISSN: 0213-8646 (Print); 2530-3791 (Online)`
2. it is on toc page https://doaj.org/toc/1575-0965
3. the journal's only ISSN is 1575-0965. As you can see it's not one of the article's ISSNs.

Need to investigate why the article is still appearing on the journal's toc page then.

**Comment by richard-jones** [comment] 2017-06-13 13:24
I've analysed this issue, and the problem is that the articles themselves contain issns from both journals.  It's confusing to look at, but consider this article:

https://doaj.org/article/01a69660279a4949811301c09ddd77be

It says on the article page that the issns are "0213-8646 (Print); 2530-3791 (Online)".  This is true /for the journal the we thinks it belongs to/.

What you can't see on this page is that the article also contains 2 issns which allow it to be related to a journal, and those are 0213-8646 and 1575-0965.  You can see this on the administrative search for that article, though:

https://doaj.org/admin/admin_site_search?source=%7B%22query%22%3A%7B%22query_string%22%3A%7B%22query%22%3A%2201a69660279a4949811301c09ddd77be%22%2C%22default_operator%22%3A%22AND%22%7D%7D%2C%22from%22%3A0%2C%22size%22%3A10%7D

When we have attempted to synchronise journal information from the owning journal to the article, we would have found two journals, RIFOP and REIFOP.  Since we can't synchronise two journals to one article, we would have picked the first result, which in this case was RIFOP.  The article then becomes formally associated with that journal.

But, since 1575-0965 is also in the article metadata, we now have a list of 3 issns that it claims association with:

* 0213-8646 - RIFOP
* 2530-3791 - RIFOP
* 1575-0965 - REIFOP

So, the article appears in both journal ToCs, which is "correct" in the sense that the ToC shows any article which asserts to belong to that ISSN.

The solution?  The articles contain wrong or inconsistent information, and there's no way that we can make a judgement call automatically as to what the correct ISSNs are.  We rely on the publisher to give us consistent information, which in this case it looks like they haven't.  The official solution is that the publisher should send through articles with the correct issn pairs.

Depending on the scale of the problem, we could also script a solution, if there's a clear rule to follow.

@ClaraDOAJ - assigning this back to you to decide what to do about it, then we can re-tag as tnm or whatever is needed to resolve it.

**Comment by ClaraDOAJ** [comment] 2017-06-13 13:41
Hello CL

We think it is better to write to the publisher so they can upload the correct metadata again.

**Closed** 2017-09-01 12:17 UTC
