### ISSUE TITLE
2405-6561 XML with software exception error- possible BUG.

### ISSUE THREAD

**Issue by ClaraDOAJ** [DOAJ/doaj#1390] opened 2017-09-21 07:35 UTC
Dear CL,

The attached xml ended up with this error. The publisher is experienced and I do not think it is an erroneus xml. Could you please have a look?
[PETLM_3_3.xml.zip](https://github.com/DOAJ/doaj/files/1320311/PETLM_3_3.xml.zip)

![image](https://user-images.githubusercontent.com/22593616/30684003-d42027f2-9eaf-11e7-86d8-aea1e19ef719.png)

Many thanks!

**Comment by richard-jones** [comment] 2017-09-21 08:27
I can't see a background job that failed around this time, so I guess this happened when the file was uploaded rather than when it was processed.  A quick skim of the file, and it looks sensible, though I have not validated it.

The journal for which this was intended is not on the test server, so I can't immediately try to replicate the issue.

@Steven-Eardley @emanuil-tolev - could one of you either or both: refresh the test server with up-to-date data so I can try this out, and check the logs for this timestamp to see if there is any more detail there.

For reference, this is the journal whose ISSN appears in the first article: https://doaj.org/toc/2405-5816

**Comment by ClaraDOAJ** [comment] 2017-09-21 08:29
Also, they have tried to upload the file several times, different days. So it was not when our system was sluggish. 

@richard-jones the journal is "Petroleum"- correct.

**Comment by richard-jones** [comment] 2017-09-21 09:59
I've just updated my dev environment for parity with live, and run through the process of uploading and ingesting this file, and it worked fine.  This would suggest that the file, upload process and background task are all behaving correctly in principle.  Could this be something in the deployment?

**Comment by richard-jones** [comment] 2017-09-21 10:00
That's on a reduced set of articles - there could be something going on, say, if a duplicate is found.  I may replicate the entire DOAJ to my machine and re-try.

**Comment by richard-jones** [comment] 2017-09-21 10:01
Though note that re-uploading the file again and re-processing it straight away works fine, and correctly detects all the duplicates.

**Comment by richard-jones** [comment] 2017-09-22 08:50
I tried several ways to reproduce this in a dev environment yesterday, and didn't encounter any problems.

@emanuil-tolev @Steven-Eardley - I think this must be a deployment environment thing, but I'm not sure what, can one of you take a look?

**Comment by Steven-Eardley** [comment] 2017-09-26 09:45
First I'll check the logs for the trace.

**Comment by richard-jones** [comment] 2017-09-26 14:03
We have now diagnosed and reproduced this in development.  It was an unfortunate and unforeseen side-effect of #1370 .  It arises because when an article is submitted to a journal with an LCC code that is incorrectly spelled, attempts to build index data for the search and subject browser fail, causing an exception.  The fix for this is in 3 parts:

1. Make the index generation code more robust to failure.  There is a PR for this already #1400 .  The consequences of this are that some articles are not going to be found by subject search for a while, but there will at least not be errors when publishers upload files

2. Run a data migration on the Journals, Articles and Applications to correct the spellings of LCC subjects stored against them.  #1370 only updated the LCC dictionary we hold, not the instances where this data has been copied for discovery and display, so that needs to be done.  When that's done all articles and journals will appear correctly in search and subject browser.

3. Change the way we handle LCC, so that we work primarily with the code, and not the text.  This may be a longer-term fix, for robustness, as it has an impact on how we calculate the index data and how we present the display.

**Comment by dommitchell** [comment] 2017-10-10 07:28
@richard-jones When should we best do (2) and (3), Is this a pre-refactoring thing?

**Comment by ClaraDOAJ** [comment] 2017-10-10 07:39
The publisher has just chased  this a couple of hours ago...

**Comment by dommitchell** [comment] 2017-10-10 07:41
> Make the index generation code more robust to failure. There is a PR for this already #1400 . The consequences of this are that some articles are not going to be found by subject search for a while, but there will at least not be errors when publishers upload files

@ClaraDOAJ I think that they should be able to now upload without problems.

**Comment by ClaraDOAJ** [comment] 2017-10-10 07:53
@dommitchell ok, will ask them now.

**Comment by richard-jones** [comment] 2017-10-10 08:55
@dommitchell - I think we are going to do (2) quite soon, so that the existing dataset is consistent.  Then we can do (3) during the refactor.

**Comment by ClaraDOAJ** [comment] 2017-10-10 11:47
I just received a confirmation email that this is sorted!

**Comment by richard-jones** [comment] 2017-11-03 15:32
@Steven-Eardley - what's the status of this one, with regard to running the spelling migration?

**Comment by richard-jones** [comment] 2017-11-07 10:24
Adding tnm label, as the spelling migration is work that should have been done when we made the spelling changes, and wasn't done then.

**Comment by Steven-Eardley** [comment] 2017-11-23 15:54
Closing this issue, because the original problem was sorted. Track changes from https://github.com/DOAJ/doaj/issues/1390#issuecomment-332208571 in https://github.com/DOAJ/doaj/issues/1447 and https://github.com/DOAJ/doaj/issues/1448

**Closed by Steven-Eardley** 2017-11-23 15:54 UTC
Labels: bug, tnm
