### ISSUE TITLE
OAI-PMH bug?

### ISSUE THREAD

**Issue by dommitchell** [DOAJ/doaj#586] opened 2015-02-24 13:59 UTC
I have tried to download metadata from DOAJ's OAI PMH server using a standard Python OAI package (version 2.4.4) but it failed each time. Please see the traceback:

Traceback (most recent call last):
  File "./download_oaipmh.py", line 117, in <module>
    download_oaipmh(base_url, output, prefix, sets)
  File "./download_oaipmh.py", line 84, in download_oaipmh
    for recno, rec in enumerate(records):
  File "/home/jindra/.virtualenvs/ef/lib/python2.6/site-packages/oaipmh/client.py", line 336, in ResumptionListGenerator
    result, token = nextBatch(token)
  File "/home/jindra/.virtualenvs/ef/lib/python2.6/site-packages/oaipmh/client.py", line 179, in nextBatch
    resumptionToken=token)
  File "/home/jindra/.virtualenvs/ef/lib/python2.6/site-packages/oaipmh/client.py", line 274, in makeRequestErrorHandling
    raise error.XMLSyntaxError(kw)
oaipmh.error.XMLSyntaxError: {'verb': 'ListRecords', 'resumptionToken': 'eyJtIjogIm9haV9kYyIsICJuIjogMTM0NDAwfQ=='}

To my understanding, all settings are fine on our side. The package I use works fine for all data downloaded via OAI PMH with the sole exception of DOAJ.

**Comment by richard-jones** [comment] 2015-02-24 14:19
Hm, not sure - could also be a bug in the client, difficult to tell without looking at both.  I just hit:

http://doaj.org/oai.article?verb=ListRecords&resumptionToken=eyJtIjogIm9haV9kYyIsICJuIjogMTM0NDAwfQ==

Which is the page it refers to, and it renders fine in my browser.

To know more we'd have to set up a new test with this client and run it until we find an error, and then we'd have somewhere to start.

**Comment by dommitchell** [comment] 2015-02-25 08:08
Could 'bad' inverted commas be breaking this?

(häufig  auch als medizinisch unerklärte Symptome bezeichnet

**Comment by richard-jones** [comment] 2015-02-25 11:21
Could be - if the problem is on our side, certainly my guess is it is an illegal character issue.  We already do quite aggressive "safety" checking on the strings that go into the XML feed, but I also I did raise an issue recently for looking at legitimate unicode characters that aren't supposed to be in XML: #561 - they don't break the outgoing XML, but some readers may throw an error if they encounter them, so this could be that problem.

I was going to look at that during the review of OAI during PVOD but if this issue is that problem rearing it's head I'll look at it asap.

**Comment by richard-jones** [comment] 2015-03-02 12:48
@emanuil-tolev - did we confirm yet whether the proposed fix worked on staging?

**Comment by emanuil-tolev** [comment] 2015-03-05 19:15
> @emanuil-tolev - did we confirm yet whether the proposed fix worked on staging?

Nope, it didn't work actually. I did mention it but there was a lot we talked about so .. :). Should have updated the issue, sorry.

```
resumption token eyJtIjogIm9haV9kYyIsICJuIjogMjY0NjAwfQ== cursor 264500/1782141
harvesting http://localhost:5050/oai.article?verb=ListRecords&resumptionToken=eyJtIjogIm9haV9kYyIsICJuIjogMjY0NjAwfQ==
resumption token eyJtIjogIm9haV9kYyIsICJuIjogMjY0NzAwfQ== cursor 264600/1782141
harvesting http://localhost:5050/oai.article?verb=ListRecords&resumptionToken=eyJtIjogIm9haV9kYyIsICJuIjogMjY0NzAwfQ==
Traceback (most recent call last):
  File "doajtest/functional/oaipmh_client_test.py", line 44, in <module>
    rt = harvest(ARTICLE_BASE_URL, rt)
  File "doajtest/functional/oaipmh_client_test.py", line 22, in harvest
    resp = requests.get(url)
  File "/opt/doaj/local/lib/python2.7/site-packages/requests/api.py", line 55, in get
    return request('get', url, **kwargs)
  File "/opt/doaj/local/lib/python2.7/site-packages/requests/api.py", line 44, in request
    return session.request(method=method, url=url, **kwargs)
  File "/opt/doaj/local/lib/python2.7/site-packages/requests/sessions.py", line 279, in request
    resp = self.send(prep, stream=stream, timeout=timeout, verify=verify, cert=cert, proxies=proxies)
  File "/opt/doaj/local/lib/python2.7/site-packages/requests/sessions.py", line 374, in send
    r = adapter.send(request, **kwargs)
  File "/opt/doaj/local/lib/python2.7/site-packages/requests/adapters.py", line 209, in send
    raise ConnectionError(e)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=5050): Max retries exceeded with url: /oai.article?verb=ListRecords&resumptionToken=eyJtIjogIm9haV9kYyIsICJuIjogMjY0NzAwfQ== (Caused by <class 'socket.error'>: [Errno 104] Connection reset by peer)
```

I'm going to rerun it again, since the one on Test succeeded on the 3rd attempt.

**Comment by emanuil-tolev** [comment] 2015-03-05 19:40
Fix deployed to live, let's see.

**Comment by emanuil-tolev** [comment] 2015-03-05 19:41
Reassigned to you @richard-jones - do we need to do anything else except go back to original asker and inform them to try again?

**Comment by dommitchell** [comment] 2015-03-06 05:41
Got this. Will ask asker to try again

**Comment by emanuil-tolev** [comment] 2015-03-06 13:50
> @emanuil-tolev - did we confirm yet whether the proposed fix worked on staging?

Also FYI it did complete on Staging without connection resets. So it finished both on Test and Staging yesterday.

**Comment by richard-jones** [comment] 2015-04-23 16:43
Ok, looks good - no more repeats of this so closing off

**Closed by richard-jones** 2015-04-23 16:43 UTC
Labels: bug
