### ISSUE TITLE
MDPI submissions failing

### ISSUE THREAD

**Issue by ClaraDOAJ** [DOAJ/doaj#1419] opened 2017-10-31 09:49 UTC
Hello CL

MDPI are trying to upload this file. Apparently there is one or more journals that are not found. I had a look at their account and there was just 1 removed journal in their account that still had the issn and not the xxxx-xxxx. But even though I changed that, they still get the same error. Can you help me, please?

data-v02-i04_20171030.xml.zip](https://github.com/DOAJ/doaj/files/1430208/data-v02-i04_20171030.xml.zip)

**Comment by ClaraDOAJ** [comment] 2017-10-31 10:50
![image](https://user-images.githubusercontent.com/22593616/32220358-b9641df0-be31-11e7-80ea-cecdf9977d8c.png)

**Comment by dommitchell** [comment] 2017-10-31 10:55
@ClaraDOAJ  Can you get details of what the error message is that they are getting? And ask them to try again tomorrow and then report back if they are getting the same message. I notice that they include multiple journals in one XML file so how do we know that the problem is with Aerospace?

They last added metadata in Sept 2017 so its strange that they cannot do it now. 

Thanks!

**Comment by ClaraDOAJ** [comment] 2017-10-31 11:25
The error they get is: "Unable to find a journal associated with your account". But the system does not tell them which one.

We don't know the problem is with Aerospace, but I wanted to check if they had any journal with the duplication issue, as this is the most common cause of this sort of problem nowadays.

**Comment by dommitchell** [comment] 2017-10-31 13:01
Except now they have got in touch with a different error message: Failed to upload file - please contact an administrator.

I am awaiting permission from them to log in to their account.

**Comment by ClaraDOAJ** [comment] 2017-10-31 13:14
Thanks, Dom! I can keep an eye on this in the next few days.

**Comment by richard-jones** [comment] 2017-11-03 17:47
Just to check, is the error message actually "Unable to find a journal associated with this article".  The message "Unable to find a journal associated with your account" doesn't exist in DOAJ, so they shouldn't ever receive that 

If that's the case, I can see what's happening here in the code.  Before we look to see whether someone is permitted to upload an article, we first extract all the metadata from the XML via a crosswalk.  This, in turn, looks up the journal to get the additional journal metadata.  If it can't find a journal /at all/, then this is the error you'd get.  This potential issue has always been there, and I guess we never noticed it, as it is so rare for someone to upload articles for ISSNs that we have never seen.

The fix for this is really just to improve the error reporting so we know which issn is causing the problem, and add it to the error report we give them.  I'll look into that shortly.

In the mean time, it's not possible to know which article is causing the issue, other than manually inspecting all the ISSNs they've given us, and seeing if they exist in DOAJ.

**Comment by richard-jones** [comment] 2017-11-03 17:49
This isn't actually a bug, it's a lacking in an error reporting feature, so I've reclassified it as high-priority.

**Comment by dommitchell** [comment] 2017-11-04 06:55
Closing this one as I've sorted it. I opened a new task re messaging here: #1422

**Closed by dommitchell** 2017-11-04 06:55 UTC
Labels: article xml, high priority
