### ISSUE TITLE
Assigning journal to Editor Group invokes Bad Gateway

### ISSUE THREAD

**Issue by dommitchell** [DOAJ/doaj#548] opened 2015-01-27 14:56 UTC
https://doaj.org/admin/suggestion/0281894b53cc4196b4bf6404cbe0c4d2#first_problem at 15.54pm (14.54 UTC)

![gate](https://cloud.githubusercontent.com/assets/5955396/5920452/ef42d674-a63c-11e4-806f-344060f59901.jpg)

It's happened to me 3 times now. 

I'm opening applications that are already in progress and assigning them to Editor group 'Dom's group'. If I hit back on my browser, unlock and close the journal is indeed assigned to the correct group

**Comment by emanuil-tolev** [comment] 2015-01-27 15:06
Does it hang there for 30s (or so) before showing you this 502 Bad Gateway screen?

**Comment by emanuil-tolev** [comment] 2015-01-27 15:08
Yeah, something weird is going on. https://rpm.newrelic.com/accounts/526071/applications/3171791/transactions#id=540963092 the application admin page has suddenly started taking 30s to load (and timing out).

**Comment by emanuil-tolev** [comment] 2015-01-27 15:12
Nothing helpful in the server logs, just an indication from the Newrelic daemon that the DOAJ app has timed out. Strange way for it to time out though, something seems to have called sys.exit - maybe not our own code, but the point is it seems the interpreter is shutting down. I'm sure it's only a symptom of what the problem actually is :). Will try locally now.

**Comment by emanuil-tolev** [comment] 2015-01-27 15:15
OK, so naturally I can't reproduce it with a random application from Staging (using same code as Live), otherwise life would be too easy.

**Comment by emanuil-tolev** [comment] 2015-01-27 15:17
Hahah, it only seems to happen to "Dom's group" @dommitchell :). I tried assigning that application you have in the original post to English1 and it worked. Switch back to Dom's group, booom.

**Comment by emanuil-tolev** [comment] 2015-01-27 15:19
Hm, I made "Dom's group" on staging (using the current live code) and assigned an application to it. But it worked :(. So still can't reproduce it..

**Comment by emanuil-tolev** [comment] 2015-01-27 15:21
I am even more confident it's "Dom's group" that causes this, and that it does not happen at random times. I just assigned that application to 5 different editor groups and Dom's group broke the page again. But only on live.

**Comment by emanuil-tolev** [comment] 2015-01-27 15:40
It's something to do with the email. @dommitchell I forgot an email was sent every time an application was reassigned, I might have emailed the editors of all the English groups and the editor of Arabic 1. My apologies to all of them - I was in a bit of a rush to get the problem fixed. More discipline should be used and tested only done on the staging environment next time (so copy over all the relevant data, in this case editor group, accounts, and application to staging, then test there). Actually I had to do this anyway to reproduce the problem, so next time I (and whoever else investigates a problem like this) should replicate it locally using data *from* live but not *on* live.

**Comment by dommitchell** [comment] 2015-01-27 15:42
Could it be because I changed the name of the group just now?

**Comment by emanuil-tolev** [comment] 2015-01-27 16:00
No .. something's wrong with your email on live. You don't have one set. Go set one?
This must be because we created your account manually (not via the form you guys have now) so you got a username and a password, but not an email address.

**Comment by emanuil-tolev** [comment] 2015-01-27 16:02
I've submitted some code for review which will make sure users get a nice message if this happens, with a magic number to give us so we can track down the error in the logs. And of course I also make sure in that code that it no longer crashes and burns when no email is specified. When it's reviewed and rolled out I'll update here.

**Comment by emanuil-tolev** [comment] 2015-01-27 16:11
The fix has been rolled out @dommitchell . If you have not yet set your email address, go try reassigning the application to another group and then to Dom's group. You'll see the new error message and the page won't break.

Otherwise fix is by going to your account and setting yourself an email address :). Feel free to close if that works out OK.

**Comment by dommitchell** [comment] 2015-01-27 16:25
Hmm, it's caching. Which page do I need to reload to stop that?

**Comment by emanuil-tolev** [comment] 2015-01-27 16:31
What do you mean? Caching shouldn't matter for this. If you're assigning Dom's group after it's already got Dom's group then nothing will happen, no email will fire, so no error will occur. You've got to assign it to a different group I'm afraid - feel free to make another test editor group.

**Closed** 2015-01-28 08:19 UTC
Labels: bug, ready for review
