### ISSUE TITLE
Embedding the search box

### ISSUE THREAD

**Issue by dommitchell** [DOAJ/doaj#100] opened 2014-02-17 13:13 UTC
Is there a way that a customer could embed our search box onto their pages. e.g. http://www.doabooks.org/doabSearchBox.html

**Comment by dommitchell** [comment] 2015-02-17 12:40
@markmacgillivray once we have moved to two servers, would load still be an issue?

**Comment by emanuil-tolev** [comment] 2015-05-29 13:15
@dommitchell re: the load issue, it's actually quite hard to know that. I expect we can only reasonably see how the load is while our pilot friends are using the newly minted widget - that is to say without doing heavier-duty scalability testing, which can take quite some effort to set up. Currently my plan regarding load is:

1. see how pilot publishers "load" the site
2. from that, make some judgements on how to improve scalability (e.g. can we simply buy a third data server, can we segregate API requests somehow) if that needs to happen
3. let it go live if there are no major concerns, and keep monitoring the load - if there are concerns we'll discuss them during the project.
4. ultimately we can always shut the widgets down in emergencies. A widget means the code for it is actually downloaded from doaj.org and then that code also queries DOAJ - stop serving the widget, stop all the widget requests. Of course that'll break it on widget users' websites.

The alternative is to simulate the kind of load the widget will generate which is just too much effort for a widget. At the end of the day it's only a smallish part of the API project. Of course if load from it becomes a sticking point we'll have to discuss options of handling that - and don't forget that beyond what we can do, we can always simply ask those whose sites are too big for us to handle, to remove the widget temporarily while we work with you to decide if we want increased capability + exposure on the very high traffic site, or go without that exposure and expenditure. That way smaller widget users can keep using it and we deal specifically with problematic users, it's not an all or nothing.

**Comment by dommitchell** [comment] 2015-05-29 13:28
Thanks! As you said:

> At the end of the day it's only a smallish part of the API project.

and I think the concerns here were from a time before we were doing the API etc. Good to have all this on the table though!

**Comment by emanuil-tolev** [comment] 2015-06-01 16:19
Duplicate of #746 . Moved my comment re load above to there.

**Closed by emanuil-tolev** 2015-06-01 16:19 UTC
Labels: enhancement, medium priority
