### ISSUE TITLE
Catalogue and Index  2399-9667

### ISSUE THREAD

**Issue by ClaraDOAJ** [DOAJ/doaj#1384] opened 2017-09-19 10:30 UTC
hello,

I added the e-issn 2399-9667 for this journal a few days ago. This journal had been accepted in DOAJ last year and according to the publisher, they had been adding metadata with their p issn 0008-7629. After the update of eissn the content published with the print issn has disappeared from the ToC. 

I think this might be a bug. Could you please have a look?

Thanks

**Comment by Steven-Eardley** [comment] 2017-09-19 12:26
It seems we always prefer EISSNs to PISSNs when generating ToC pages:

```python
        # if there is an E-ISSN, redirect to it
        # if not, but there is a P-ISSN, redirect to it
        # if neither ISSN is present, continue loading the page
        issn = bibjson.get_one_identifier(bibjson.E_ISSN)
        if not issn:
            issn = bibjson.get_one_identifier(bibjson.P_ISSN)
        if issn:
            return redirect(url_for('doaj.toc', identifier=issn, volume=volume, issue=issue), 301)
```

So when we go to the ToC page for that journal it has the following query to display the articles:
```
https://doaj.org/toc/2399-9667?source={"query":{"filtered":{"filter":{"bool":{"must":[{"term":{"index.issn.exact":"2399-9667"}},{"term":{"_type":"article"}}]}},"query":{"match_all":{}}}},"from":0,"size":100}
```

i.e. it only cares about the EISSN when it's looking for the articles to display. By adding the EISSN, that is now considered the canonical identifier for the ToC page and its articles.

An article should get its data from the journal it's associated with, so I expect both the EISSN and PISSN should be on the article records. This usually happens when the article is imported, but since your EISSN change was more recent, the changes aren't visible in the older articles.

It should probably be the case that any changes to a journal's metadata should be propagated to its articles - I'll leave it to @richard-jones to determine whether this is a bug or an enhancement.

We could also consider whether the ToC query should be less strict; such as an OR search for both of its ISSNs - there may be some unintended consequences for this, particularly in cases where ISSNs overlap between publications, if that can happen.

**Comment by Steven-Eardley** [comment] 2017-09-26 09:50
The article sync background job should have run - this bug would account for this issue.

**Comment by richard-jones** [comment] 2017-09-26 09:51
This is a recent error from running the article_cleanup_sync:

2017-09-03T00:52:06.238628Z -- Caught in job runner during run: Traceback (most recent call last): File "/home/cloo/repl/production/doaj/src/doaj/portality/background.py", line 47, in execute background_task.run() File "/home/cloo/repl/production/doaj/src/doaj/portality/tasks/article_cleanup_sync.py", line 49, in run for a in esprit.tasks.scroll(conn, 'article', q={"query" : {"match_all" : {}}, "sort" : ["_doc"]}, page_size=100, keepalive='5m'): File "/home/cloo/repl/production/doaj/src/esprit/esprit/tasks.py", line 58, in scroll results = raw.unpack_result(sresp) File "/home/cloo/repl/production/doaj/src/esprit/esprit/raw.py", line 167, in unpack_result j = requests_response.json() File "/home/cloo/repl/production/doaj/local/lib/python2.7/site-packages/requests/models.py", line 604, in json return json.loads(self.text or self.content) File "/usr/lib/python2.7/json/__init__.py", line 338, in loads return _default_decoder.decode(s) File "/usr/lib/python2.7/json/decoder.py", line 366, in decode obj, end = self.raw_decode(s, idx=_w(s, 0).end()) File "/usr/lib/python2.7/json/decoder.py", line 384, in raw_decode raise ValueError("No JSON object could be decoded") ValueError: No JSON object could be decoded

**Comment by richard-jones** [comment] 2017-09-26 09:52
Probably increase the keep-alive parameter on the scroll, and also run this script more regularly than once per month

**Comment by richard-jones** [comment] 2017-09-26 09:56
May also increase the page size

**Comment by emanuil-tolev** [comment] 2017-09-26 09:59
If those suggestions don't work, consider sharding. Run 16 much smaller article sync tasks: one for articles whose IDs start with `0`, one for IDs starting `1` ... until one for IDs starting `f`.

**Comment by richard-jones** [comment] 2017-10-10 09:54
Job ran successfully now, so this should be fix, can we confirm with the publisher?

**Comment by Steven-Eardley** [comment] 2017-10-10 09:57
The ToC now has articles from 2016 as well as 2017, so it's looking positive.

**Comment by richard-jones** [comment] 2017-11-03 15:31
@ClaraDOAJ - just assigning this one to you, as I believe it's now fixed.  The issue is just that if a journal's ISSNs change, then some time is needed for this information to synchronise down to the articles.  That's now happened so everything should be good.

**Closed** 2018-03-19 21:06 UTC
Labels: bug, ready for review
