### ISSUE TITLE
News page duplicates all posts

### ISSUE THREAD

**Issue by greboun** [DOAJ/doaj#917] opened 2015-10-30 16:39 UTC
website shows duplicated entries  dd 10/30/2015 5.39 EST

![image](https://cloud.githubusercontent.com/assets/12031556/10851758/2d350eba-7f2d-11e5-9c60-0067c7833431.png)

**Comment by richard-jones** [comment] 2015-11-17 13:04
We've reset the news feed and re-run it a few times, and everything seems to be fine.  We have checked the code and it all passes muster, so it's not clear what caused the duplication issue.

Closing for the time being, but we'll keep an eye on the news feed and re-visit if the issue returns.

**Closed by richard-jones** 2015-11-17 13:04 UTC
Labels: bug

**Comment by emanuil-tolev** [comment] 2015-11-17 13:05
This should be fixed. I don't think it's a code problem so if this occurs again we will need to look at it in a lot more detail (in the sense of trying to reproduce it, and it could be a number of factors including hardware load and resources, which are notoriously hard to reproduce). This incident (and the news fetch logs we keep) is actually looking like an important data point in an ongoing analysis of DOAJ's performance and stability.

**Comment by dommitchell** [comment] 2015-11-18 10:23
Great! Thanks!
